const jokeList = [
    "<p> O que o lápis falou para o papel?</p> <p>-  Ôh, você só me desaponta</p>",
    "<p>O que a Lua disse ao Sol?</p><p>- Nossa, você é tão grande e ainda não te deixam sair à noite.</p>",
    "<p>O que uma pulga disse à outra?</p><p>- Vamos a pé ou esperamos pelo cachorro?</p>",
    "<p>O que um fantasma disse ao outro?</p><p>- Você acredita em gente?</p>",
    "<p>Você sabe por que a água foi presa?</p><p>- Porque ela matou a sede.</p>",
    "<p>Por que o professor usava óculos escuros na sala de aula?</p><p>- Porque os seus alunos eram brilhantes.</p>",
    "<p>Qual a diferença entre o penico e a panela?</p><p>- Se você não sabe, nunca me convide para almoçar na sua casa.</p>",
    "<p>Por que o motoboy foi demitido?</p><p>- Porque ele não estava “capacetado” pro trabalho.</p>",
    "<p>Qual é o doce preferido dos átomos?</p><p>- É o pé de moléculas.</p>",
    "<p>Qual é o fim da picada?</p><p>- Quando o mosquito vai embora.</p>",
    "<p>O que um pato disse ao outro?</p><p>- Estamos empatados.</p>",
    "<p>Por que os fantasmas são péssimos para contar mentiras?</p><p>- Porque você pode ver através deles.</p>",
    "<p>Por que o astronauta não conseguiu reservar um quarto de hotel na Lua?</p><p>- Porque ela estava cheia.</p>",
    "<p>Por que os robôs nunca sentem medo?</p><p>- Porque eles têm nervos de aço.</p>",
    "<p>Por que as girafas sempre tiram notas ruins?</p><p>- Elas vivem com a cabeça na lua.</p>",
    "<p>O que é um pontinho vermelho na árvore?</p><p>- Um morangotango.</p>",
    "<p>Por que a galinha não bate em outros animais?</p><p>- Porque elas têm pena.</p>",
    "<p>Um peixe perguntou ao outro: o que o seu pai faz?</p><p>O outro respondeu: Nada e o seu?</p><p>- Nada também.</p>",
    "<p>Uma senhora está em sua varanda com seu gato</p><p>Um homem se aproxima e pergunta: Arranha?</p><p>Ela responde: Não, gato.</p>",
    "<p>Um homem foi até a farmácia e perguntou: Você tem remédio para barata?</p><p>O vendedor repondeu: O que a barata tem?</p>",
    "<p>O que uma árvore disse para a outra?</p><p>- Nos deixaram plantadas.</p>",
    "<p>- Mamãe, os meninos na escola estão me chamando de distraído!</p><p>- Joãozinho, você mora na casa da frente…</p>",
    "<p>Um dia o Joãozinho perguntou a sua mãe: mamãe, os bombons de chocolate sobem pelas paredes?</p><p>Ela respondeu: não, Joãozinho, os bombons não andam!</p><p>Joãozinho disse: ah, bom… então acho que comi uma barata!</p>",
    "<p>- Joãozinho, se eu tenho seis laranjas em uma mão e cinco na outra, o que tenho no total?</p><p>- Mãos muito grandes professora.</p>",
    "<p>O Joãozinho diz ao pai: pai tenho uma notícia boa e outra ruim.</p><p>O pai diz: tá bom, conte a boa primeiro.</p><p>Joãozinho: passei em todas as matérias na escola.</p><p>O pai: e qual a má?</p><p>Joãozinho: era mentira.</p>",
    "<p>- Papai, o que o senhor sente tendo um filho tão bonito?</p><p>- Não sei Joãozinho, pergunta ao seu avô.</p>",
    "<p>- Mamãe, você sabia que vermelho é a cor do amor? Pergunta o Joãozinho.</p><p>- Sei sim meu filho, por quê?</p><p>- Porque eu te amo, toma aqui meu boletim.</p>",
    "<p>A professora pergunta ao Joãozinho: arroz é com S ou com Z?</p><p>O Joãozinho responde: aqui na escola eu não sei professora, mas lá em casa é com feijão.</p>",
    "<p>Um homem diz: minha senhora, quer me fazer o favor de pedir ao seu filho que pare de me imitar?</p><p>A mulher: Joãozinho, eu já disse pra você parar de bancar o bobo!</p>",
    "<p>O que é o que é que o pernilongo tem que é maior que o elefante?</p><p>- O nome.</p>",
    "<p>O que é o que é que se compra para comer, mas a gente não come?</p><p>- O garfo.</p>",
    "<p>O que é o que é que é seu, mas é muito mais usado pelos outros?</p><p>- O seu nome.</p>",
    "<p>O que é o que é que o lápis disse para o papel?</p><p>- Você vive me desapontando.</p>",
    "<p>O que é o que é que não faz nada de errado, mas vive apanhando?</p><p>- O tambor.</p>",
    "<p>O que é o que é feito para andar, mas nunca anda?</p><p>- A rua.</p>",
    "<p>O que é o que é que dá muitas voltas e não sai do lugar?</p><p>- O relógio.</p>",
    "<p>O que é o que é que a impressora disse para a outra?</p><p>- Essa folha é sua ou é impressão minha?</p>",
    "<p>O que é o que é que anda com os pés na cabeça?</p><p>- O piolho.</p>",
    "<p>O que é o que é que mesmo atravessando o rio não se molha?</p><p>- A ponte.</p>",
    "<p>O que é o que é que de dia tem quatro pernas e de noite tem seis?</p><p>- A cama.</p>",
    "<p>O que é o que é que entra na água e não se molha?</p><p>- A sombra</p>"
];

export default jokeList;
